config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: ''
  
  root to: 'home#index'
  
  devise_scope :admin do
    get 'login', to: 'devise/sessions#new', as: :new_main_admin_session
    post 'login', to: 'devise/sessions#create', as: :main_admin_session
    delete 'logout', to: 'devise/sessions#destroy', as: :main_admin_destroy
  end

  authenticated :admin do
    resources :admins
    resources :profiles
    resources :skills
    resources :contacts
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  mount_uploader :icon, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :image, ImageUploader

  def self.instance
    Profile.first || Profile.create(name: 'Full Name', description: 'Job Title')
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  mount_uploader :icon, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = Contact.all.order(:created_at)
  end

  def show
  end
  
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: 'Contact was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: 'Contact was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_path, notice: 'Contact was successfully destroyed.' }
    end
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:icon, :social, :link)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @profile = Profile.instance
    @skills = Skill.all.order(:created_at)
    @contacts = Contact.all.order(:created_at)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_path(@profile), notice: 'Profile was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to :new, notice: 'Profile was successfully destroyed.' }
    end
  end

  private

  def set_profile
    @profile = Profile.instance
  end

  def profile_params
    params.require(:profile).permit(:image, :name, :description)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  def index
    @skills = Skill.all.order(:created_at)
  end

  def show
  end
  
  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to skills_path, notice: 'Skill was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to skills_path, notice: 'Skill was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_path, notice: 'Skill was successfully destroyed.' }
    end
  end

  private

  def set_skill
    @skill = Skill.find(params[:id])
  end

  def skill_params
    params.require(:skill).permit(:icon, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<div class="flex w-100 h-100 flex-column justc-c align-c">
  <%= form_with(model: @contact, local: true, class: 'form-white') do |f| %>
    <% if @contact.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

        <ul>
        <% @contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="field flex align-c">
      <%= f.label :icon %>
      <div class="flex flex-1 align-c justc-c">
        <%= f.file_field :icon %>
      </div>
    </div>

    <div class="field flex align-c">
      <%= f.label :social %>
      <div class="flex flex-1 align-c justc-c">
        <%= f.text_field :social %>
      </div>
    </div>

    <div class="field flex align-c">
      <%= f.label :link %>
      <div class="flex flex-1 align-c justc-c">
        <%= f.text_field :link %>
      </div>
    </div>

    <div class="actions w-100 flex align-c justc-c">
      <%= f.submit 'Save', class: 'btn btn-white' %>
    </div>
  <% end %>
</div>

app/views/contacts/edit.html.erb
<section>
  <div class="control-bar">
      <div class="flex justc-c align-c">
        <h3 class="flex-1">Editing Contact</h3>
        <div class="flex-1 tar">
          <%= link_to '← Back', contacts_path, class: 'btn btn-secundary' %>
          <%= link_to 'Show', @contact, class: 'btn btn-secundary' %>
        </div>
      </div>
  </div>

  <%= render 'form' %>
</section>

app/views/contacts/index.html.erb
<section>
  <p id="notice"><%= notice %></p>

  <div class="control-bar">
    <div class="flex justc-c align-c">
      <h3 class="flex-1">Contacts</h3>
      <div class="flex-1 tar">
        <%= link_to 'Create', new_contact_path, class: 'btn btn-secundary' %>
      </div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Icon</th>
        <th>Social</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= image_tag contact.icon.url %></td>
          <td><%= contact.social %></td>
          <td><%= link_to 'View', contact %> <%= link_to 'Edit', edit_contact_path(contact) %> <%= link_to 'Delete', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</section>

app/views/contacts/new.html.erb
<section>
  <div class="control-bar">
    <div class="flex justc-c align-c">
      <h3 class="flex-1">Create Contact</h3>
      <div class="flex-1 tar">
        <%= link_to '← Back', contacts_path, class: 'btn btn-secundary' %>
      </div>
    </div>
  </div>

  <%= render 'form' %>

</section>

app/views/contacts/show.html.erb
<section>
  <div class="control-bar">
    <div class="flex justc-c align-c">
      <h3 class="flex-1"><%= @contact.social %></h3>
      <div class="flex-1 tar">
      <%= link_to '← Back', contacts_path, class: 'btn btn-secundary' %>
        <%= link_to 'Edit', edit_contact_path(@contact), class: 'btn btn-secundary' %>
      </div>
    </div>
  </div>

  <div class="flex w-100 h-100 flex-column justc-c align-c">
    <p id="notice"><%= notice %></p>

    <% if @contact.icon.url %>
      <p>
        <%= image_tag @contact.icon.url, class: 'w-150px' %>
      </p>
    <% end %>

    <div class="pt-10">
      <p>
        <%= @contact.social %>
      </p>
    </div>

    <div class="pt-10">
      <p>
        <%= link_to 'Open', @contact.link, target: "_blank", class: 'btn btn-secundary' %>
      </p>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<main>
  <section class="s-1 flex align-c justc-end">
    <div class="tar">
      <%= image_tag @profile.image.url, class: 'ig-profile'%>
      <h1><%= @profile.name %></h1>
      <h2><%= @profile.description %></h2>
    </div>
    <div class="bot-fade"></div>
  </section>

  <section class="s-2 tac">
    <h1>What I do</h1>
    <ul class="skills flex justc-c align-c f-wrap">
      <% @skills.each do |skill| %>
        <li>
          <%= image_tag skill.icon.url, alt:skill.name %>
          <p><%= skill.name %></p>
        </li>
      <% end %>
    </ul>
  </section>
</main>

<footer class="flex">
  <p>Contact me</p>
  <ul class="social flex flex-1 justc-end">
    <% @contacts.each do |contact| %>
      <li>
        <%= link_to(contact.link, target:'_blank') do %>
          <img src="<%= contact.icon.url %>" alt="<%= contact.social %>">
        <% end %>
      </li>
    <% end %>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header>
  <section>
    <nav>
      <%= link_to 'Home', root_path %>
      <%= link_to 'Profile', profile_path(Profile.instance) %>
      <%= link_to 'Skills', skills_path %>
      <%= link_to 'Contacts', contacts_path %>
      <%= link_to 'Logout', :main_admin_destroy, method: :delete, data: { confirm: 'Are you sure?' } %>
    </nav>
  </section>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=yes">

    <meta property="og:title" content="Ricardo Gonçalves - Web Developer" />
    <meta property="og:description" content="Web Developer based in Lisbon" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="Ricardo Gonçalves - Web Developer" />
    <meta property="og:image" content="https://riagoncalves-website.s3-eu-west-1.amazonaws.com/thumbnail.jpg">

    <meta name="twitter:title" content="Ricardo Gonçalves">
    <meta name="twitter:description" content="Web Developer based in Lisbon">
    <meta name="twitter:image" content="https://riagoncalves-website.s3-eu-west-1.amazonaws.com/thumbnail.jpg">

    <meta name="description" content="Web Developer based in Lisbon">
    <meta name="keywords" content="HTML,CSS,Rails,JavaScript" />
    <meta name="author" content="Ricardo Gonçalves"><meta name="twitter:description" content="Web Developer based in Lisbon">
  
    <title>Ricardo Gonçalves | Web Developer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if admin_signed_in? %>
      <%= render 'layouts/header' %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<div class="flex w-100 h-100 flex-column justc-c align-c">
  <%= form_with(model: @profile, local: true, class: 'form-white') do |f| %>
    <% if @profile.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

        <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="field flex align-c">
      <%= f.label :image %>
      <div class="flex flex-1 align-c justc-c">
        <%= f.file_field :image %>
      </div>
    </div>

    <div class="field flex align-c">
      <%= f.label :name %>
      <div class="flex flex-1 align-c justc-c">
        <%= f.text_field :name %>
      </div>
    </div>

    <div class="field flex align-c">
      <%= f.label :description %>
      <div class="flex flex-1 align-c justc-c">
        <%= f.text_field :description %>
      </div>
    </div>

    <div class="actions w-100 flex align-c justc-c">
      <%= f.submit 'Save', class: 'btn btn-white' %>
    </div>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<section>
  <div class="control-bar">
      <div class="flex justc-c align-c">
        <h3 class="flex-1">Editing Profile</h3>
        <div class="flex-1 tar">
          <%= link_to 'Show', @profile, class: 'btn btn-secundary' %>
        </div>
      </div>
  </div>

  <%= render 'form' %>

</section>

app/views/profiles/show.html.erb
<section>
  <div class="control-bar">
    <div class="flex justc-c align-c">
      <h3 class="flex-1"><%= @profile.try(:name) %></h3>
      <div class="flex-1 tar">
        <%= link_to 'Edit', edit_profile_path(@profile), class: 'btn btn-secundary' %>
      </div>
    </div>
  </div>

  <div class="flex w-100 h-100 flex-column justc-c align-c">
    <p id="notice"><%= notice %></p>

    <% if @profile.image.url %>
      <p>
        <%= image_tag @profile.image.url %>
      </p>
    <% end %>

    <div class="pt-10">
      <p>
        <%= @profile.name %>
      </p>
    </div>

    <div class="pt-10">
      <p>
        <%= @profile.description %>
      </p>
    </div>

  </div>
</section>

app/views/skills/_form.html.erb
<div class="flex w-100 h-100 flex-column justc-c align-c">
  <%= form_with(model: @skill, local: true, class: 'form-white') do |f| %>
    <% if @skill.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

        <ul>
        <% @skill.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="field flex align-c">
      <%= f.label :icon %>
      <div class="flex flex-1 align-c justc-c">
        <%= f.file_field :icon %>
      </div>
    </div>

    <div class="field flex align-c">
      <%= f.label :name %>
      <div class="flex flex-1 align-c justc-c">
        <%= f.text_field :name %>
      </div>
    </div>

    <div class="actions w-100 flex align-c justc-c">
      <%= f.submit 'Save', class: 'btn btn-white' %>
    </div>
  <% end %>
</div>

app/views/skills/edit.html.erb
<section>
  <div class="control-bar">
      <div class="flex justc-c align-c">
        <h3 class="flex-1">Editing Skill</h3>
        <div class="flex-1 tar">
          <%= link_to '← Back', skills_path, class: 'btn btn-secundary' %>
          <%= link_to 'Show', @skill, class: 'btn btn-secundary' %>
        </div>
      </div>
  </div>

  <%= render 'form' %>
</section>

app/views/skills/index.html.erb
<section>
  <p id="notice"><%= notice %></p>

  <div class="control-bar">
    <div class="flex justc-c align-c">
      <h3 class="flex-1">Skills</h3>
      <div class="flex-1 tar">
        <%= link_to 'Create', new_skill_path, class: 'btn btn-secundary' %>
      </div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Icon</th>
        <th>Name</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @skills.each do |skill| %>
        <tr>
          <td><%= image_tag skill.icon.url %></td>
          <td><%= skill.name %></td>
          <td><%= link_to 'View', skill %> <%= link_to 'Edit', edit_skill_path(skill) %> <%= link_to 'Delete', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/skills/new.html.erb
<section>
  <div class="control-bar">
    <div class="flex justc-c align-c">
      <h3 class="flex-1">Create Skill</h3>
      <div class="flex-1 tar">
        <%= link_to '← Back', skills_path, class: 'btn btn-secundary' %>
      </div>
    </div>
  </div>

  <%= render 'form' %>

</section>

app/views/skills/show.html.erb
<section>
  <div class="control-bar">
    <div class="flex justc-c align-c">
      <h3 class="flex-1"><%= @skill.name %></h3>
      <div class="flex-1 tar">
      <%= link_to '← Back', skills_path, class: 'btn btn-secundary' %>
        <%= link_to 'Edit', edit_skill_path(@skill), class: 'btn btn-secundary' %>
      </div>
    </div>
  </div>
  <div class="flex w-100 h-100 flex-column justc-c align-c">
    <p id="notice"><%= notice %></p>
    
     <% if @skill.icon.url %>
      <p>
        <%= image_tag @skill.icon.url, class: 'w-150px' %>
      </p>
    <% end %>
    <div class="pt-10">
      <p>
        <%= @skill.name %>
      </p>
    </div>
  </div>
</section>